name: fast_near_duplicate_img_src_py3
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2019.1.23=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.3.9=py36_0
  - cycler=0.10.0=py36_0
  - dbus=1.13.6=h746ee38_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.13=h23475e2_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.3=199
  - jasper=2.0.14=h07fcdf6_1
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.0.1=py36hf484d3e_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.36=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - matplotlib=3.0.3=py36h5429711_0
  - mkl=2019.3=199
  - mkl_fft=1.0.10=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - natsort=5.5.0=py36_0
  - ncurses=6.1=he6710b0_1
  - numpy=1.16.2=py36h7e9f1db_0
  - numpy-base=1.16.2=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - openssl=1.1.1b=h7b6447c_1
  - pandas=0.24.2=py36he6710b0_0
  - patsy=0.5.1=py36_0
  - pcre=8.43=he6710b0_0
  - pillow=6.0.0=py36h34e0f95_0
  - pip=19.0.3=py36_0
  - pixman=0.38.0=h7b6447c_0
  - py-opencv=3.4.2=py36hb342d67_1
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - python=3.6.8=h0371630_0
  - python-dateutil=2.8.0=py36_0
  - pytz=2019.1=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.20.3=py36hd81dba3_0
  - scipy=1.2.1=py36h7c811a0_0
  - seaborn=0.9.0=py36_0
  - setuptools=41.0.0=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - sqlite=3.27.2=h7b6447c_0
  - statsmodels=0.9.0=py36h035aef0_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.2=py36h7b6447c_0
  - tqdm=4.31.1=py36_1
  - wheel=0.33.1=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
      - atomicwrites==1.3.0
      - attrs==19.1.0
    - imagehash==4.0
      - importlib-metadata==0.15
      - more-itertools==7.0.0
    - opencv-contrib-python==4.0.0.21
      - pluggy==0.12.0
      - py==1.8.0
      - pytest==4.5.0
    - pywavelets==1.0.3
    - versioneer==0.18
      - wcwidth==0.1.7
      - zipp==0.5.1
